"""
SAGE Coder Agent
----------------
Input:  TaskNode dict
Output: PatchRequest (written to disk via ToolExecutionEngine)

Primary model: qwen2.5-coder:14b-instruct-q4_K_M
Fallback:      gpt-4o

TDD discipline (enforced by template):
- Write failing test FIRST
- Then minimal code to pass
- Any code written before a test is deleted on review

Pipeline:
  1. Load coder.md template
  2. Inject task + memory + user rules context
  3. Call Ollama → get JSON PatchRequest
  4. Validate schema
  5. Route to ToolExecutionEngine → file written to disk
  6. Return result dict
"""

import json
from pathlib import Path

try:
    import ollama  # type: ignore
except ModuleNotFoundError:  # pragma: no cover
    ollama = None

from sage.debug_mode_log import agent_debug_log
from sage.agents.llm_parse import parse_patch_json
from sage.cli.branding import print_agent_line
from sage.orchestrator.model_router import ModelRouter
from sage.protocol.schemas import PatchRequest
from sage.protocol.schemas import AgentInsight
from sage.llm.ollama_safe import chat_with_timeout, OllamaTimeout
from sage.rl.ucb_bandit import get_global_bandit

TEMPLATE_PATH = Path(__file__).parent.parent / "prompt_engine" / "templates" / "coder.md"
PROJECT_RULES_PATH = Path(".sage") / "rules.md"
CODER_RULES_PATH = Path(".sage") / "rules.coder.md"
LEGACY_RULES_PATH = Path(".sage-rules.md")


def _load_template() -> str:
    if TEMPLATE_PATH.exists():
        return TEMPLATE_PATH.read_text()
    return ""


def _load_user_rules() -> str:
    parts: list[str] = []
    for p in (PROJECT_RULES_PATH, CODER_RULES_PATH, LEGACY_RULES_PATH):
        try:
            if p.exists():
                txt = p.read_text(errors="ignore").strip()
                if txt:
                    parts.append(txt)
        except Exception:
            continue
    if not parts:
        return "No project-specific rules defined."
    # Project rules should come first; agent-specific + legacy last.
    return "\n\n".join(parts)


def _normalise_data(raw_data) -> dict:
    """
    Normalise the model output into our flat PatchRequest dict.
    Handles:
      - flat dict  {"file": ..., "patch": ...}
      - RFC-6902 JSON Patch array  [{"op":"add","path":"/app.py","value":"..."}]
    """
    if isinstance(raw_data, list):
        # Take first add/replace operation
        for op in raw_data:
            if op.get("op") in ("add", "replace"):
                return {
                    "file": op.get("path", "output.py").lstrip("/"),
                    "operation": "create" if op.get("op") == "add" else "edit",
                    "patch": op.get("value", ""),
                    "reason": "Generated by coder agent",
                    "epistemic_flags": [],
                }
    return raw_data  # already a flat dict


def _to_patch_request(data: dict) -> PatchRequest:
    # Normalize common key aliases from small model outputs
    file_val = (
        data.get("file")
        or data.get("filepath")
        or data.get("path")
        or data.get("filename", "output.py")
    )
    # Strip leading slash (model may emit RFC JSON Patch absolute paths)
    file_val = str(file_val).lstrip("/")
    patch_val = (
        data.get("patch")
        or data.get("content")
        or data.get("code")
        or data.get("body")
        or data.get("value", "")
    )
    # Ensure patch_val is a string — model sometimes returns a nested dict
    if not isinstance(patch_val, str):
        patch_val = json.dumps(patch_val, indent=2)
    return PatchRequest(
        file=file_val,
        operation=data.get("operation", "create"),
        patch=patch_val,
        reason=data.get("reason", ""),
        epistemic_flags=data.get("epistemic_flags", []),
    )


class CoderAgent:
    def __init__(self):
        self.router = ModelRouter()
        self.template = _load_template()
        # NOTE: ToolExecutionEngine is used by `tool_executor` in the workflow.
        # The coder agent must only emit PatchRequest objects.

    # ── Private helpers ──────────────────────────────────────────────────────

    @staticmethod
    def _read_existing_file(file_path: str, max_chars: int = 3000) -> str:
        """
        Safely read *file_path* and return its content (truncated to *max_chars*).

        Returns an empty string if the file does not exist or cannot be read.
        Never raises.
        """
        try:
            p = Path(file_path)
            if not p.is_file():
                return ""
            text = p.read_text(errors="replace")
            if len(text) > max_chars:
                return text[:max_chars] + f"\n... (truncated, {len(text)} chars total)"
            return text
        except Exception:
            return ""

    @staticmethod
    def _extract_referenced_files(task: dict, memory: dict) -> list[str]:
        """
        Extract file paths that should be read before generating code.

        Sources checked (in priority order):
        1. architect_blueprint in memory → files list
        2. task["target_file"] if set
        3. Simple heuristic: first path-like token in task["description"]
        """
        files: list[str] = []

        # 1. Architect blueprint
        blueprint = memory.get("architect_blueprint") or {}
        if isinstance(blueprint, dict):
            for key in ("files", "target_files", "file_list"):
                val = blueprint.get(key)
                if isinstance(val, list):
                    files.extend(str(f) for f in val if f)
                elif isinstance(val, str) and val:
                    files.append(val)

        # 2. Explicit target_file on the task
        target = task.get("target_file") or task.get("file") or ""
        if target and str(target).strip():
            files.append(str(target).strip())

        # 3. Heuristic: look for a path-like token in description (e.g. src/foo.py)
        import re as _re
        desc = task.get("description", "")
        for token in _re.findall(r'[\w./\-]+\.(?:py|ts|js|json|toml|yaml|yml|txt|md)', desc):
            files.append(token)

        # Deduplicate while preserving order
        seen: set[str] = set()
        unique: list[str] = []
        for f in files:
            if f not in seen:
                seen.add(f)
                unique.append(f)
        return unique

    def _build_existing_code_context(self, task: dict, memory: dict) -> str:
        """
        Return an EXISTING_CODE_CONTEXT block to inject into the coder prompt.

        Reads every referenced file and formats the content as a fenced block.
        Returns an empty string if no referenced files exist on disk.
        """
        file_paths = self._extract_referenced_files(task, memory)
        blocks: list[str] = []
        for fp in file_paths:
            content = self._read_existing_file(fp)
            if content:
                blocks.append(
                    f"### Existing file: {fp}\n```\n{content}\n```"
                )
        if not blocks:
            return ""
        return (
            "\n\nEXISTING_CODE_CONTEXT (read these before writing — match style exactly):\n\n"
            + "\n\n".join(blocks)
        )

    @staticmethod
    def _build_conventions_context(session_memory: dict) -> str:
        """
        Return a CONVENTIONS_TO_MATCH block if codebase_brief has conventions.
        Returns empty string otherwise.
        """
        codebase_brief = session_memory.get("codebase_brief") or {}
        if not isinstance(codebase_brief, dict):
            return ""
        conventions = codebase_brief.get("conventions")
        if not conventions:
            return ""
        if isinstance(conventions, list):
            conv_text = "\n".join(f"- {c}" for c in conventions)
        elif isinstance(conventions, dict):
            conv_text = json.dumps(conventions, indent=2)
        else:
            conv_text = str(conventions)
        return f"\n\nCONVENTIONS_TO_MATCH (follow these exactly — do not deviate):\n{conv_text}"

    @staticmethod
    def _build_symbols_context(session_memory: dict) -> str:
        """
        Return an EXISTING_SYMBOLS block and reuse instruction if semantic index is available.
        Returns empty string otherwise.
        """
        codebase_brief = session_memory.get("codebase_brief") or {}
        if not isinstance(codebase_brief, dict):
            return ""
        if not codebase_brief.get("semantic_index_built"):
            return ""
        symbols_summary = codebase_brief.get("symbols_summary")
        if not symbols_summary:
            return ""
        if isinstance(symbols_summary, list):
            symbols_text = "\n".join(f"  - {s}" for s in symbols_summary[:50])
        elif isinstance(symbols_summary, dict):
            symbols_text = json.dumps(symbols_summary, indent=2)
        else:
            symbols_text = str(symbols_summary)[:2000]
        return (
            "\n\nEXISTING_SYMBOLS (semantic index available):\n"
            + symbols_text
            + "\n\nINSTRUCTION: Before creating any new function, check the EXISTING_SYMBOLS "
            "list above and reuse existing ones instead of reimplementing."
        )

    def run(
        self,
        task: dict,
        memory: dict,
        mode: str = "auto",
        failure_count: int = 0,
        universal_prefix: str = "",
        insight_sink=None,
    ) -> dict:
        """
        Execute a coding task. Returns:
        {
          "status": "completed" | "failed",
          "file": str,
          "operation": str,
          "reason": str,
          "error": str | None,
        }
        """

        # Small helper: emit AgentInsight packets if an orchestrator sink exists.
        def _emit(
            insight_type: str,
            *,
            severity: str,
            content: str,
            requires_orchestrator_action: bool = False,
        ) -> None:
            if insight_sink is None:
                return
            try:
                insight_sink.ingest(
                    AgentInsight(
                        agent="coder",
                        task_id=str(task.get("id", "")),
                        insight_type=insight_type,
                        content=(content or "")[:2000],
                        severity=severity,
                        requires_orchestrator_action=requires_orchestrator_action,
                    )
                )
            except Exception:
                # Observability must never break orchestration.
                return

        # Tier 1 RL (MVP): discrete prompt/model strategies chosen via UCB.
        primary_model, fallback_model = self.router.get_primary_fallback("coder")
        bandit = get_global_bandit()

        strategies = {
            # Conservative: lower temperature + stricter "minimal diff" instruction.
            "coder:primary:conservative": {
                "model": primary_model,
                "temperature": 0.05,
                "system_suffix": "Prefer minimal diffs. Do not refactor unrelated code; change only what is required to satisfy the task.",
            },
            "coder:primary:standard": {
                "model": primary_model,
                "temperature": 0.10,
                "system_suffix": "Implement the task as needed. Refactors are allowed when they improve correctness or maintainability.",
            },
            "coder:fallback:conservative": {
                "model": fallback_model,
                "temperature": 0.05,
                "system_suffix": "Prefer minimal diffs. Do not refactor unrelated code; change only what is required to satisfy the task.",
            },
            "coder:fallback:standard": {
                "model": fallback_model,
                "temperature": 0.10,
                "system_suffix": "Implement the task as needed. Refactors are allowed when they improve correctness or maintainability.",
            },
        }

        candidate_keys = list(strategies.keys())
        task_complexity_score = float(task.get("task_complexity_score", 0.0) or 0.0)
        if self.router.should_use_fallback(
            "coder",
            task_complexity_score=task_complexity_score,
            failure_count=failure_count,
        ):
            # Spec-aligned: restrict exploration to fallback strategies.
            candidate_keys = ["coder:fallback:conservative", "coder:fallback:standard"]

        # Orchestrator intelligence feed: high composite risk → prefer fallback models.
        if bool(memory.get("intel_force_fallback")):
            candidate_keys = [k for k in candidate_keys if "fallback" in k] or [
                "coder:fallback:standard",
                "coder:fallback:conservative",
            ]

        strategy_key = bandit.select(strategy_keys=candidate_keys)
        chosen = strategies[strategy_key]
        model = chosen["model"]
        temperature = float(chosen["temperature"])
        system_suffix = str(chosen["system_suffix"])
        user_rules = _load_user_rules()

        _emit(
            "decision",
            severity="low",
            content=(
                f"Coder strategy selected: strategy_key={strategy_key}, "
                f"model={model}, temperature={temperature:.2f}"
            ),
        )

        # ── Build context-enriched prompt ─────────────────────────────────────
        # session_memory may be nested under memory["session_memory"] or be memory itself
        session_memory: dict = (
            memory.get("session_memory")
            if isinstance(memory.get("session_memory"), dict)
            else memory
        )

        existing_code_ctx = self._build_existing_code_context(task, memory)
        conventions_ctx = self._build_conventions_context(session_memory)
        symbols_ctx = self._build_symbols_context(session_memory)

        system = (
            self.template.replace("{task_description}", task.get("description", ""))
            .replace("{project_memory_summary}", json.dumps(memory, indent=2))
            .replace("{user_rules}", user_rules)
        )
        # Inject enriched context blocks BEFORE the system suffix
        if existing_code_ctx:
            system = system + existing_code_ctx
        if conventions_ctx:
            system = system + conventions_ctx
        if symbols_ctx:
            system = system + symbols_ctx

        if universal_prefix:
            system = universal_prefix + "\n\n" + system
        # Append strategy-specific instruction after the universal prefix.
        system = system + "\n\n" + system_suffix

        print_agent_line("Coder", f"Using model: {model}")
        print_agent_line("Coder", f"Task: {task.get('description', '')[:80]}")

        # ── Call Ollama ────────────────────────────────────────────────────────
        if ollama is None:
            _emit(
                "risk",
                severity="high",
                content="ollama module not available; cannot generate PatchRequest.",
                requires_orchestrator_action=True,
            )
            err = "ollama module not available"
            return {"status": "failed", "file": "", "operation": "", "reason": "", "error": err}
        try:
            response = chat_with_timeout(
                model=model,
                messages=[
                    {"role": "system", "content": system},
                    {
                        "role": "user",
                        "content": (
                            f"Implement the following task.\n\n"
                            f"TASK: {task.get('description', '')}\n\n"
                            "Return ONLY a JSON PatchRequest object. "
                            "No prose outside the JSON."
                        ),
                    },
                ],
                options={"temperature": temperature},
                timeout_s=None,
            )
        except (OllamaTimeout, RuntimeError, Exception) as e:
            _emit(
                "risk",
                severity="high",
                content=f"LLM call failed/timeout: {str(e)[:1200]}",
                requires_orchestrator_action=True,
            )
            return {"status": "failed", "file": "", "operation": "", "reason": "", "error": str(e)}

        msg = response.get("message") or {}
        raw = msg.get("content", "") if isinstance(msg, dict) else ""

        # ── Parse ──────────────────────────────────────────────────────────────
        try:
            raw_data = parse_patch_json(raw)
            data = _normalise_data(raw_data)
            patch_req = _to_patch_request(data)
        except (ValueError, json.JSONDecodeError, KeyError, TypeError) as e:
            print_agent_line("Coder", f"Parse failed: {e}")
            _emit(
                "risk",
                severity="high",
                content=f"Failed to parse model output into PatchRequest: {str(e)[:1200]}",
                requires_orchestrator_action=True,
            )
            return {
                "status": "failed",
                "file": "",
                "operation": "",
                "reason": str(e),
                "error": str(e),
            }

        if not str(patch_req.patch or "").strip():
            err = "model returned empty patch content"
            print_agent_line("Coder", err)
            _emit(
                "risk",
                severity="high",
                content=err,
                requires_orchestrator_action=True,
            )
            return {
                "status": "failed",
                "file": patch_req.file,
                "operation": patch_req.operation,
                "reason": err,
                "error": err,
            }

        print_agent_line("Coder", f"PatchRequest ready → {patch_req.file} ({patch_req.operation})")
        agent_debug_log(
            hypothesis_id="H_coder",
            location="coder.py:patch_ready",
            message="coder_patch_ready",
            data={
                "file": patch_req.file,
                "operation": patch_req.operation,
                "patch_len": len(patch_req.patch or ""),
            },
        )
        if patch_req.epistemic_flags:
            print_agent_line("Coder", f"Flags: {', '.join(patch_req.epistemic_flags)}")

        _emit(
            "observation",
            severity="low",
            content=(
                f"PatchRequest ready: file={patch_req.file}, operation={patch_req.operation}, "
                f"epistemic_flags={patch_req.epistemic_flags}"
            ),
        )

        # Workflow `tool_executor` will apply this patch with safety checks.
        return {
            "status": "patch_ready",
            "patch_request": vars(patch_req),
            "file": patch_req.file,
            "operation": patch_req.operation,
            "reason": patch_req.reason,
            "error": None,
            "model_used": model,
            "strategy_key": strategy_key,
            "epistemic_flags": patch_req.epistemic_flags,
        }
